workflows:
  react-native-ios:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 16.13.2
      xcode: 16.0
      cocoapods: 1.11.2
    scripts:
      # Installiere eine neuere Ruby-Version
      - name: Install Ruby and CocoaPods
        script: |
          brew install rbenv
          rbenv install 3.1.0
          rbenv global 3.1.0
          ruby -v  # Überprüfen der Ruby-Version
          sudo gem install cocoapods
          cd ios
          pod install --repo-update
      # Xcode Build
      - name: xCode build
        script: |
          cd ios
          xcodebuild clean archive -workspace YourProject.xcworkspace -scheme YourScheme -archivePath YourArchivePath.xcarchive CODE_SIGNING_ALLOWED=NO | xcpretty
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
