workflows:
  ios:
    name: Build and Test iOS App
    max_build_duration: 60
    platform: ios
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install
      - name: Run tests
        script: |
          npm test
    artifacts:
      - build/ios/Build/Products/Debug-iphonesimulator/YourApp.app
    build:
      ios:
        archive:
          provisioning_profile: "YourProvisioningProfile"
          distribution_certificate: "YourDistributionCertificate"
        # Alternative: wenn du Expo nutzt, kann es so aussehen:
        # expo:
        #   build:
        #     ios:
        #       app_store_connect_api_key: "YOUR_API_KEY"
