workflows:
  ios:
    name: Build iOS app
    instance_type: mac_mini # Korrekt: mac_mini, mac_mini_m1, mac_mini_m2, mac_pro, linux, linux_x2, windows_x2
    environment:
      vars:
        EXPO_PASSWORD: EncryptedPassword
    steps:
      - name: Checkout code
        action: checkout
      - name: Install dependencies
        run: |
          npm install
      - name: Build iOS app
        run: |
          cd ios && pod install --repo-update
          npx react-native run-ios --configuration Release
      - name: Export .ipa file
        run: |
          xcodebuild -workspace ios/DoneWithIt.xcworkspace -scheme DoneWithIt -sdk iphoneos -configuration Release clean archive -archivePath $HOME/DoneWithIt.xcarchive
          xcodebuild -exportArchive -archivePath $HOME/DoneWithIt.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $HOME/DoneWithIt.ipa
      - name: Upload .ipa to build artifacts
        upload: $HOME/DoneWithIt.ipa
