workflows:
  ios:
    name: iOS build
    platform: ios
    dependencies:
      pre-cache: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/YourApp.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $PWD/build/YourApp.xcarchive -exportPath $PWD/build/YourApp.ipa -exportOptionsPlist ios/exportOptions.plist
