workflows:
  ios:
    name: Build iOS app
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -configuration Release
    artifacts:
      - build/ios/Build/Products/Release-iphoneos/YourApp.app
