workflows:
  ios:
    name: Build iOS app
    instance_type: mac_mini_m2
    environment:
      vars:
        EXPO_PASSWORD: EncryptedPassword # Optional, falls du Umgebungsvariablen benötigst
    scripts:
      - name: Checkout code
        script: git clone https://github.com/Spotygo/App.git
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install --repo-update
      - name: Build iOS app
        script: |
          npx react-native run-ios --configuration Release
      - name: Export .ipa file
        script: |
          xcodebuild -workspace ios/DoneWithIt.xcworkspace -scheme DoneWithIt -sdk iphoneos -configuration Release clean archive -archivePath $HOME/DoneWithIt.xcarchive
          xcodebuild -exportArchive -archivePath $HOME/DoneWithIt.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $HOME/DoneWithIt.ipa
      - name: Upload .ipa to build artifacts
        script: |
          cp $HOME/DoneWithIt.ipa /artifacts/
