workflows:
  react-native-ios:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 16.13.2
      xcode: 16.0
      cocoapods: 1.11.2
    scripts:
      # Installiere Ruby und CocoaPods
      - name: Install Ruby and CocoaPods
        script: |
          brew install rbenv
          rbenv install 3.1.0
          rbenv global 3.1.0
          ruby -v
          sudo gem install cocoapods
          cd ios
          pod install --repo-update
      # Fixiere 'react_native_pods.rb' Pfad
      - name: Fix React Native Pods Path
        script: |
          sed -i '' 's|require Pod::Executable.execute_command("node", ["-p",|require File.join(File.dirname(`node -e '\''require.resolve("react-native/package.json")'\''`), "scripts/react_native_pods.rb")|' ios/Podfile
      # Xcode Build
      - name: xCode build
        script: |
          cd ios
          xcodebuild clean archive -workspace YourProject.xcworkspace -scheme YourScheme -archivePath YourArchivePath.xcarchive CODE_SIGNING_ALLOWED=NO | xcpretty
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
